[package]
name = "luhnoxide"
version = "0.1.0"
edition = "2024"
authors = ["Dr. Xenith QuantumWeather<docqw@glorvo.com>"]
description = "A tool to identify valid credit card numbers in files using the Luhn algorithm"

[dependencies]
clap = "2.33"
regex = "1.5"
